apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker.fullname" . }}-secret
  labels:
    app: {{ include "worker.name" . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: "{{ $value }}"
{{- end }}
